version: "3.8"

volumes:
  data:

services:
  virtualradar:
    build: .
    container_name: virtualradar
    volumes:
      - data:/root/.local/share/VirtualRadar
    ports:
      - 8080:8080
    restart: always
